server:
  port: 8706

spring:
  application:
    name: qdgx-dmp-test

      
feign: 
  hystrix:
    enable: true
    command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            thread:
              timeoutInMilliseconds: 100000
ribbon: 
  ReadTimeout: 60000  
  ConnectTimeout: 60000

management: 
  endpoints:
    web:
      exposure:
        include: "*"